"""001 - Exercises and relations

Revision ID: 116ac8ac2000
Revises: 
Create Date: 2023-10-25 00:26:25.555627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '116ac8ac2000'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('muscle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_muscle_id'), 'muscle', ['id'], unique=False)
    op.create_index(op.f('ix_muscle_name'), 'muscle', ['name'], unique=False)
    op.create_table('exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_id'), 'exercise', ['id'], unique=False)
    op.create_index(op.f('ix_exercise_name'), 'exercise', ['name'], unique=False)
    op.create_table('muscle_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_muscle_category_id'), 'muscle_category', ['id'], unique=False)
    op.create_index(op.f('ix_muscle_category_name'), 'muscle_category', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_muscle_category_name'), table_name='muscle_category')
    op.drop_index(op.f('ix_muscle_category_id'), table_name='muscle_category')
    op.drop_table('muscle_category')
    op.drop_index(op.f('ix_exercise_name'), table_name='exercise')
    op.drop_index(op.f('ix_exercise_id'), table_name='exercise')
    op.drop_table('exercise')
    op.drop_index(op.f('ix_muscle_name'), table_name='muscle')
    op.drop_index(op.f('ix_muscle_id'), table_name='muscle')
    op.drop_table('muscle')
    # ### end Alembic commands ###
