"""005_exercise_description

Revision ID: 32f7e5e34254
Revises: bfc1b735fa8f
Create Date: 2024-02-07 22:46:16.089594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32f7e5e34254'
down_revision: Union[str, None] = 'bfc1b735fa8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('description', sa.String(), nullable=True))
    op.create_index(op.f('ix_exercise_description'), 'exercise', ['description'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercise_description'), table_name='exercise')
    op.drop_column('exercise', 'description')
    # ### end Alembic commands ###
