"""004_muscle_and_muscle_category_relation

Revision ID: bfc1b735fa8f
Revises: 5935f37521dc
Create Date: 2024-02-06 23:51:17.305576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfc1b735fa8f'
down_revision: Union[str, None] = '5935f37521dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('muscle', sa.Column('muscle_category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'muscle', 'muscle_category', ['muscle_category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'muscle', type_='foreignkey')
    op.drop_column('muscle', 'muscle_category_id')
    # ### end Alembic commands ###
